parallel-jobs = 1
cli-source = "j-hc/revanced-cli"

[Photos]
app-name = "Google Photos ReVanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos"
patches-source = "revanced/revanced-patches"
version = "auto"
arch = "arm64-v8a"
build-mode = "apk"

[YouTube]
app-name = "YouTube ReVanced Extended"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube"
patches-source = "reddxae/revanced-extended-patches"
patches-version = "5.6.2"
integrations-source = "inotia00/revanced-integrations"
version = "19.16.39"
arch = "arm64-v8a"
build-mode = "apk"
included-patches = "'Return YouTube Username'"
excluded-patches = "'Hide accessibility controls dialog' 'Enable debug logging'"
patcher-args = "-e 'Custom branding name for YouTube' -OappName=YouTube -e 'Theme' -OdarkThemeBackgroundColor=@android:color/black -OlightThemeBackgroundColor=@android:color/white -e 'Visual preferences icons for YouTube' -OsettingsMenuIcon=revanced -OapplyToAll=true -e 'Custom branding icon for YouTube' -OappIcon=youtube -OrestoreOldSplashAnimation=true -e 'Overlay buttons' -OiconType=thin -OwiderButtonsSpace=true -OchangeTopButtons=true -e 'Settings for YouTube' -OrvxSettingsLabel='ReVanced Extended' -OinsertPosition=@string/about_key -e 'SponsorBlock' -OoutlineIcon=true"
